name: Convert gfw.list

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ main ]
    paths:
      - "rule/gfw-raw.list"
  workflow_dispatch:

jobs:
  convert_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download GFW List
      run: |
        curl -fsSL -o rule/gfwlist.txt https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
        echo "gfwlist Downloaded "
    - name: Decode and save to gfw-raw.list
      run: |
        base64 -d rule/gfwlist.txt > rule/gfw-raw.list
        echo "Decoded adn Created gfw-raw.list"
    - name: Process domain file
      run: |
        echo "Processing domain file..."
        # 设置原始文件和转换后的文件名
        original_file=rule/gfw-raw.list
        converted_file=rule/gfw.list
        # 删除转换后的文件，如果存在的话
        if [ -f "$converted_file" ]; then
          rm "$converted_file"
        fi
        # 逐行读取原始文件并进行处理
        while IFS= read -r line; do
          if [[ "$line" == "@@"* || "$line" == "!"* ]]; then
            continue  # 跳过 @@ 开头和 ! 开头的行
          elif [[ "$line" =~ ^\|https?:// ]]; then
            # 使用正则表达式提取域名
            domain=$(echo "$line" | sed -E 's/^\|https?:\/\/([^/]+).*$/\1/')
            echo "Processed DOMAIN-SUFFIX, $domain"
            echo "DOMAIN-SUFFIX,$domain" >> "$converted_file" 
          elif [[ "$line" =~ ^\|\| ]]; then
            # 替换 || 开头的行为 DOMAIN,域名
            domain=$(echo "$line" | sed 's/^||//')
            echo "Processed DOMAIN, $domain"
            echo "DOMAIN,$domain" >> "$converted_file"
          elif [[ "$line" =~ ^\. ]]; then
            # 替换 . 开头的行为 DOMAIN-SUFFIX,域名
            domain=$(echo "$line" | cut -c 2-)
            echo "Processed DOMAIN-SUFFIX, $domain"
            echo "DOMAIN-SUFFIX,$domain" >> "$converted_file"
          else
            # 处理没有前缀的行
            if [[ "$line" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "Processed IP-CIDR: $line"
              echo "IP-CIDR,$line/32" >> "$converted_file"
            else
              echo "Processed DOMAIN: $line"
              echo "DOMAIN,$line" >> "$converted_file"
            fi
          fi
        done < "$original_file"
        echo "Domain processing completed."
        
    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add rule/gfw.list
        git status
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update gfw.list
        branch: main
