name: Convert gfw.list

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ main ]
    path:
      - "gfw-raw.list"

jobs:
  convert_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download GFW List
          run: |
            curl -fsSL -o gfwlist.txt https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

    - name: Decode and save to gfw-raw.list
      run: |
        base64 -d gfwlist.txt > gfw-raw.list


    - name: Process domain file
      run: |
        # 设置原始文件和转换后的文件名
        original_file=gfw-raw.list
        converted_file=gfw.list

        # 删除转换后的文件，如果存在的话
        if [ -f "$converted_file" ]; then
          rm "$converted_file"
        fi

        # 逐行读取原始文件并进行处理
        while IFS= read -r line; do
          if [[ "$line" == "@@"* || "$line" == "!"* ]]; then
            continue  # 跳过 @@ 开头和 ! 开头的行
          elif [[ "$line" == "|"* ]]; then
            # 使用正则表达式提取域名
            domain=$(echo "$line" | sed -E 's/^\|https?:\/\/([^/]+).*$/\1/')

            # 输出格式为 DOMAIN-SUFFIX,域名
            echo "DOMAIN-SUFFIX,$domain" >> "$converted_file"
          elif [[ "$line" == "||"* ]]; then
            # 替换 || 开头的行为 DOMAIN,域名
            domain=$(echo "$line" | cut -c 3-)
            echo "DOMAIN,$domain" >> "$converted_file"
          elif [[ "$line" == "."* ]]; then
            # 替换 . 开头的行为 DOMAIN-SUFFIX,域名
            domain=$(echo "$line" | cut -c 2-)
            echo "DOMAIN-SUFFIX,$domain" >> "$converted_file"
          fi
        done < "$original_file"

        # 显示转换后的文件内容
        echo "Converted domain list:"
        cat "$converted_file"

    - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Convert gfw.list
          branch: main
