name: Extract Clash Nodes

on:
  push:
    branches: [ main ]

jobs:
  extract_nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl python3-pip
          pip3 install PyYAML

      - name: Extract Clash Nodes
        run: |
          # Replace <SUBSCRIPTION-URL> with your subscription URL
          curl -sL https://knmvc.site/N2o9/CddhK/ch | python3 -c '
          import sys, yaml
          config = yaml.safe_load(sys.stdin)
          nodes = config.get("proxies", [])
          with open("sub.list", "w") as f:
            for node in nodes:
              f.write(node["name"] + " = " + node["server"] + ":" + str(node["port"]) + "\n")'
          
      - name: Print nodes
        run: cat sub.list
