name: extract-lemon-list
on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    paths:
      - 'kuainingmeng/lemon.site'
jobs:
  extract-lemon-list:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Read lemon.site
      run: |
        url=$(cat kuainingmeng/lemon.site)
        curl "$url" -o kuainingmeng/lemon.sub
      working-directory: ${{ github.workspace }}
    - name: Decode lemon.sub
      run: |
        base64 -d kuainingmeng/lemon.sub > kuainingmeng/lemon.list
      working-directory: ${{ github.workspace }}
    - name: Commit changes
      run: |
        git config --global user.email "wang_zi_mo@!63.com"
        git config --global user.name "fqw000"
        git add kuainingmeng/lemon.sub kuainingmeng/lemon.list
        git commit -m "Update lemon.sub and lemon.list"
        git push
