#  使用说明
# extract-lemon-list.yml：  
# 见readme

name: extract_lemon_list
on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: [ main ]
    path:
      - "lemon.site"
jobs:
  read-and-save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Read and save content
      run: |
          url=$(cat lemon.site)
          echo "url=$url" >> $GITHUB_ENV
          echo "" > lemon.sub
          echo "" > lemon.list
          curl -L "$url" -o lemon.sub
          cat lemon.sub | base64 -d > lemon.list
          
          url2=$(cat lemon.site | sed 's/vrn/ch/g')
          echo "url2=$url2" >> $GITHUB_ENV
          echo "" > lemon.yaml
          curl -L "$url2" -o lemon.yaml
          
          echo "" > lemonlite.yaml
          cat lemon.yaml | perl -ne 'print unless /^proxy-group/../^$/' > lemonlite.yaml
          cat lemonlitebanner.yaml >> lemonlite.yaml

          echo "" > lemonnode.yaml
          cat lemon.yaml | perl -ne 'print unless /^proxy-group/../^$/' > lemonnode.yaml
          
#        curl https://knmvc.site/N2o9/CddhK/vrn -o lemon.sub
#        cat lemon.sub | base64 -d > lemon.list
    - name: Commit changes
      run: |
        git config --global user.email "wang_zi_mo@163.com"
        git config --global user.name "fqw000"
        git add lemon.sub lemon.list lemon.yaml lemonlite.yaml lemonnode.yaml
        git commit -m "Add lemon.sub lemon.list lemon.yaml lemonlite.yaml lemonnode.yaml"
        git push
