name: Update QX Lists

on:
  push:
    paths:
      - 'rule/reject.list'
      - 'rule/proxy.list'
      - 'rule/gfw.list'
    branches: [ main ]
  workflow_dispatch:

env:
  SED_COMMANDS: |
    s/DOMAIN/HOST/
    s/URL-REGEX/# URL-REGEX/
  FILES_TO_UPDATE: reject proxy gfw

jobs:
  update-lists:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Update QX Lists
      run: |
        set -e  # 遇到错误时立即退出

        update_list() {
          local src_file="rule/$1.list"
          local dest_file="rule/$1-qx.list"

          if [ -f "$dest_file" ]; then
            echo "$dest_file exists, clearing contents."
            > "$dest_file"
          else
            echo "$dest_file does not exist, creating new file."
            touch "$dest_file"
          fi

          temp_file=$(mktemp)
          url_regex_temp=$(mktemp)
          cp "$src_file" "$temp_file"

          while IFS= read -r cmd; do
            if [ -n "$cmd" ]; then  # 过滤掉空命令
              echo "Applying sed command: $cmd"
              sed -i "$cmd" "$temp_file"
              if [ $? -ne 0 ]; then
                echo "Error applying sed command: $cmd"
                cat "$temp_file"
                exit 1
              fi
            fi
          done <<< "$SED_COMMANDS"

          # 提取所有 # URL-REGEX 行并删除它们
          grep '^# URL-REGEX' "$temp_file" > "$url_regex_temp"
          sed -i '/^# URL-REGEX/d' "$temp_file"

          cat "$temp_file" >> "$dest_file"
          echo "------URL-REGEX未处理---------" >> "$dest_file"
          cat "$url_regex_temp" >> "$dest_file"
          rm "$temp_file" "$url_regex_temp"
          
          echo "$dest_file updated successfully."
        }

        for file in $FILES_TO_UPDATE; do
          update_list $file
        done
      
    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add rule/*-qx.list
        git status
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update QX Lists
        branch: main
