name: Convert gfw.list

on:
  schedule:
    - cron: '0 */3 * * *'  # Run every 3 hours
  push:
    branches: [ main ]
    paths:
      - "rule/gfw-raw.list"
  workflow_dispatch:

jobs:
  convert_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download GFW List
      run: |
        curl -fsSL -o rule/gfwlist.txt https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
        echo "Downloaded gfwlist.txt"

    - name: Decode and save to gfw-raw.list
      run: |
        base64 -d rule/gfwlist.txt > rule/gfw-raw.list
        echo "Decoded and saved to gfw-raw.list"

    - name: Process domain file
      run: |
        echo "Processing domain file..."
        original_file=rule/gfw-raw.list
        converted_file=rule/gfw.list
        
        if [ -f "$converted_file" ]; then
          rm "$converted_file"
        fi
        
        # Loop through each line in the original file
        while IFS= read -r line; do
          # Skip lines starting with @@, [ or !
          if [[ "$line" == "@@"* || "$line" == "["* || "$line" == "!"* ]]; then
            continue
          fi
          
          # Remove 'http://' and 'https://' from the beginning of the line
          line=$(echo "$line" | sed -E 's/^https?:\/\///')
          
          # Process lines starting with . as DOMAIN-SUFFIX
          if [[ "$line" =~ ^\.[a-zA-Z0-9-_]+\.[a-zA-Z0-9-_.]+$ ]]; then
            domain=$(echo "$line" | sed -E 's/^\.([a-zA-Z0-9-_]+\.[a-zA-Z0-9-_.]+)/DOMAIN-SUFFIX,\1/')
            echo "Processed DOMAIN-SUFFIX: $domain"
            echo "$domain" >> "$converted_file"
            continue
          fi
          
          # Process IP-CIDR lines
          if [[ "$line" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3} ]]; then
            echo "Processed IP-CIDR: $line"
            echo "IP-CIDR,$line" >> "$converted_file"
            continue
          fi
          
          # Process DOMAIN lines using regex for general domains
          if [[ "$line" =~ ^([a-zA-Z0-9-_]+\.)+[a-zA-Z0-9][a-zA-Z0-9-_]+\.[a-zA-Z]{2,11}$ ]]; then
            echo "Processed DOMAIN: $line"
            echo "DOMAIN,$line" >> "$converted_file"
            continue
          fi
          
          # Process lines starting with '||' as DOMAIN-SUFFIX
          if [[ "$line" =~ ^\|\|([a-zA-Z0-9-_]+\.[a-zA-Z0-9-_.]+\.[a-zA-Z]{2,11}) ]]; then
            domain=$(echo "$line" | sed -E 's/^\|\|([a-zA-Z0-9-_]+\.[a-zA-Z0-9-_.]+\.[a-zA-Z]{2,11}).*/DOMAIN-SUFFIX,\1/')
            echo "Processed DOMAIN-SUFFIX: $domain"
            echo "$domain" >> "$converted_file"
            continue
          fi
          
          # Process lines starting with '|' as DOMAIN
          if [[ "$line" =~ ^\|([a-zA-Z0-9-_]+\.[a-zA-Z0-9-_.]+\.[a-zA-Z]{2,11}) ]]; then
            domain=$(echo "$line" | sed -E 's/^\|([a-zA-Z0-9-_]+\.[a-zA-Z0-9-_.]+\.[a-zA-Z]{2,11}).*/DOMAIN,\1/')
            echo "Processed DOMAIN: $domain"
            echo "$domain" >> "$converted_file"
            continue
          fi
          
          # Skip any lines that don't match the above patterns
          echo "Skipped line: $line"
          
        done < "$original_file"
        
        echo "Domain processing completed."

    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add rule/gfw.list
        git status

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update gfw.list
        branch: main
