name: process gfw.list

on:
  schedule:
    - cron: '0 */48 * * *'  # 每48小时运行一次
  push:
    branches: [ main ]
    paths:
      - "rule/gfw-raw.list"
  workflow_dispatch:

jobs:
  convert_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and Decode GFW List
      run: |
        curl -fsSL -o rule/gfwlist.txt https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
        echo "Downloaded gfwlist.txt"
        base64 -d rule/gfwlist.txt > rule/gfw-raw.list
        echo "Decoded and saved to gfw-raw.list"

    - name: Process domain file
      run: |
        echo "Processing domain file..."
        original_file=rule/gfw-raw.list
        converted_file=rule/gfw.list

        if [ -f "$converted_file" ]; then
          rm "$converted_file"
        fi

        process_line() {
          local line=$1
          
          if [[ "$line" == "@@"* || "$line" == "["* || "$line" == "!"* ]]; then
            return
          fi

          line=$(echo "$line" | sed -E 's|https?://||g')

          if [[ "$line" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}.* ]]; then
            domain=$(echo "$line" | grep -Eo '^([0-9]{1,3}\.){3}[0-9]{1,3}')
            echo "IP-CIDR,$domain" >> "$converted_file"
          elif [[ "$line" =~ ^\..* ]]; then
            domain=$(echo "$line" | cut -c 2- | sed -E 's/\/.*//')
            echo "DOMAIN-SUFFIX,$domain" >> "$converted_file"
          elif [[ "$line" =~ ^\|\|.* ]]; then
            domain=$(echo "$line" | cut -c 3- | sed -E 's/\/.*//')
            echo "DOMAIN-SUFFIX,$domain" >> "$converted_file"
          elif [[ "$line" =~ ^\|[^\|].* ]]; then
            domain=$(echo "$line" | cut -c 2- | sed -E 's/\/.*//')
            if [[ "$domain" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
              echo "IP-CIDR,$domain" >> "$converted_file"
            else
              echo "DOMAIN,$domain" >> "$converted_file"
            fi
          elif [[ "$line" =~ ^.+\.[^/]+ ]]; then
            domain=$(echo "$line" | sed -E 's/\/.*//')
            echo "DOMAIN,$domain" >> "$converted_file"
          else
            echo "Skipped line: $line"
          fi
        }

        while IFS= read -r line; do
          process_line "$line"
        done < "$original_file"

        echo "Domain processing completed."

    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add rule/gfw.list
        git status

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update gfw.list
        branch: main
