name: Update QX Lists

on:
  push:
    paths:
      - 'rule/reject.list'
      - 'rule/proxy.list'
    branches: [ main ]
  workflow_dispatch:

env:
  SED_COMMANDS: |
    s/DOMAIN/HOST/
    s/URL-REGEX/# URL-REGEX/
jobs:
  update-lists:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Update reject-qx.list
      run: |
        if [ -f 'rule/reject-qx.list' ]; then
          echo "rule/reject-qx.list exists, clearing contents."
          > 'rule/reject-qx.list'
        else
          echo "rule/reject-qx.list does not exist, creating new file."
          touch 'rule/reject-qx.list'
        fi
        
        temp_file=$(mktemp)
        cp rule/reject.list "$temp_file"
        while IFS= read -r cmd; do
          echo "Applying sed command: $cmd"
          sed -i "$cmd" "$temp_file"
        done <<< "$SED_COMMANDS"
        
        cat "$temp_file" >> 'rule/reject-qx.list'
        rm "$temp_file"
        
        echo "rule/reject-qx.list updated successfully."
      
    - name: Update proxy-qx.list  
      run: |
        if [ -f 'rule/proxy-qx.list' ]; then
          echo "rule/proxy-qx.list exists, clearing contents."
          > 'rule/proxy-qx.list'
        else
          echo "rule/proxy-qx.list does not exist, creating new file."
          touch 'rule/proxy-qx.list'
        fi
        
        temp_file=$(mktemp)
        cp rule/proxy.list "$temp_file"
        while IFS= read -r cmd; do
          echo "Applying sed command: $cmd"
          sed -i "$cmd" "$temp_file"
        done <<< "$SED_COMMANDS"
        
        cat "$temp_file" >> 'rule/proxy-qx.list'
        rm "$temp_file"
        
        echo "rule/proxy-qx.list updated successfully."
        
    - name: Stage changes
      run: |
        echo "Staging changes..."
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add rule/reject-qx.list rule/proxy-qx.list
        git status
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update QX Lists
        branch: main
