name: Update QX Lists

on:
  push:
    paths:
      - 'rule/reject.list'
      - 'rule/proxy.list'
    branches: [ main ]
  workflow_dispatch:

env:
  SED_COMMANDS: |
    s/DOMAIN/HOST/
    s/URL-REGEX/# URL-REGEX/

jobs:

  update-lists:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Update reject-qx.list
      run: |
        # 检查 rule/reject-qx.list 文件是否存在
        if [ -f 'rule/reject-qx.list' ]; then
          # 清空文件内容
          > 'rule/reject-qx.list'
        else
          # 创建新文件
          touch 'rule/reject-qx.list'
        fi
        
        # 创建临时文件
        temp_file=$(mktemp)
        
        # 应用 sed 命令到临时文件
        cp rule/reject.list "$temp_file"
        while IFS= read -r cmd; do
          sed -i "$cmd" "$temp_file"
        done <<< "$SED_COMMANDS"
        
        # 将临时文件内容追加到目标文件
        cat "$temp_file" >> 'rule/reject-qx.list'
        rm "$temp_file"
      
    - name: Update proxy-qx.list  
      run: |
        # 检查 rule/proxy-qx.list 文件是否存在
        if [ -f 'rule/proxy-qx.list' ]; then
          # 清空文件内容
          > 'rule/proxy-qx.list'
        else
          # 创建新文件
          touch 'rule/proxy-qx.list'
        fi
        
        # 创建临时文件
        temp_file=$(mktemp)
        
        # 应用 sed 命令到临时文件
        cp rule/proxy.list "$temp_file"
        while IFS= read -r cmd; do
          sed -i "$cmd" "$temp_file"
        done <<< "$SED_COMMANDS"
        
        # 将临时文件内容追加到目标文件
        cat "$temp_file" >> 'rule/proxy-qx.list'
        rm "$temp_file"
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update QX Lists
        branch: main
