name: Update QX Lists

on:
  push:
    paths:
      - 'rule/reject.list'
      - 'rule/proxy.list'
    branches: [ main ]
  workflow_dispatch:

env:
  SED_COMMANDS: |
    - s/DOMAIN/HOST/
    - s/URL-REGEX/# URL-REGEX/

jobs:

  update-lists:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Update reject-qx.list
      run: |
        # 检查 rule/reject-qx.list 文件是否存在
        if [ -f 'rule/reject-qx.list' ]; then
          # 清空文件内容
          > 'rule/reject-qx.list'
        else
          # 创建新文件
          touch 'rule/reject-qx.list'
        fi
        
        # 遍历 sed 命令数组并应用到 rule/reject.list
        for cmd in $(echo "$SED_COMMANDS" | tr '\n' ' '); do
          sed -e "$cmd" rule/reject.list >> 'rule/reject-qx.list'
        done
      
    - name: Update proxy-qx.list  
      run: |
        # 检查 rule/proxy-qx.list 文件是否存在
        if [ -f 'rule/proxy-qx.list' ]; then
          # 清空文件内容
          > 'rule/proxy-qx.list'
        else
          # 创建新文件
          touch 'rule/proxy-qx.list'
        fi
        
        # 遍历 sed 命令数组并应用到 rule/proxy.list
        for cmd in $(echo "$SED_COMMANDS" | tr '\n' ' '); do
          sed -e "$cmd" rule/proxy.list >> 'rule/proxy-qx.list'
        done
        
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update QX Lists
        branch: ${{ github.head_ref }}
