name: read-and-save
on:
  schedule:
    - cron: "0 */3 * * *"
  push:
    paths:
      - "lemon.sub"
jobs:
  read-and-save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Read and save content
      run: |
        curl https://knmvc.site/N2o9/CddhK/vrn -o lemon.sub
        cat lemon.sub | base64 -d > lemon.list
    - name: Commit changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add lemon.sub lemon.list
        git commit -m "Add lemon.sub and lemon.list"
        git push
