name: Update Subscriptions

on:
  schedule:
    - cron: '0 */3 * * *'
  repository_dispatch:
    types: [update_subscriptions]

jobs:
  update_subscriptions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Run script to update subscriptions
        run: |
          python .github/workflows/update_subscriptions.py

      - name: Commit and push changes
        run: |
          git config --local user.email "wang_zi_mo@163.com"
          git config --local user.name "fqw000"
          git add kuainingmeng/loon.list kuainingmeng/clash.yaml kuainingmeng/xray.list
          git commit -m "Update subscriptions" || exit 0
          git push
